# Description: Sort method arguments to place required parameters before optional parameters.
sortParamsByRequiredFlag: "true"

# Description: Sort model properties to place required parameters before optional parameters.
sortModelPropertiesByRequiredFlag: "true"

# Description: Whether to ensure parameter names are unique in an operation (rename parameters that are not).
ensureUniqueParams: "true"

# Description: boolean, toggles whether unicode identifiers are allowed in names or not, default is false
allowUnicodeIdentifiers: "false"

# Description: Add form or body parameters to the beginning of the parameter list.
prependFormOrBodyParameters: "false"

# Description: This flag is used by OpenAPITools codegen to influence the processing of the discriminator attribute in OpenAPI documents. This flag has no impact if the OAS document does not use the discriminator attribute. The default value of this flag is set in each language-specific code generator (e.g. Python, Java, go...)using the method toModelName. Note to developers supporting a language generator in OpenAPITools; to fully support the discriminator attribute as defined in the OAS specification 3.x, language generators should set this flag to true by default; however this requires updating the mustache templates to generate a language-specific discriminator lookup function that iterates over {{#mappedModels}} and does not iterate over {{children}}, {{#anyOf}}, or {{#oneOf}}.
# Available Values:
#    true
#         The mapping in the discriminator includes descendent schemas that allOf inherit from self and the discriminator mapping schemas in the OAS document.
#    false
#         The mapping in the discriminator includes any descendent schemas that allOf inherit from self, any oneOf schemas, any anyOf schemas, any x-discriminator-values, and the discriminator mapping schemas in the OAS document AND Codegen validates that oneOf and anyOf schemas contain the required discriminator and throws an error if the discriminator is missing.
legacyDiscriminatorBehavior: "true"

# Description: python package name (convention: snake_case).
packageName: apis_server

# Description: python package version.
packageVersion: 1.0.0

# Description: controller package
controllerPackage: controllers

# Description: default controller
defaultController: default

# Description: support python2
supportPython2: "false"

# Description: TCP port to listen to in app.run
serverPort: 8080

# Description: use the nose test framework
useNose: "false"

# Description: put python sources in this subdirectory of output folder (defaults to "" for). Use this for src/ layout.
pythonSrcRoot: ""
