# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from apis_server.serializers.base_model_ import Model
from apis_server.serializers.run_spec_serializer import RunSpecSerializer
from apis_server.serializers.workspace_metadata_serializer import WorkspaceMetadataSerializer
from apis_server import util


class RunSerializer(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, metadata=None, spec=None, id=None, state=None, uptime=None, create_at=None, last_update=None):  # noqa: E501
        """RunSerializer - a model defined in OpenAPI

        :param metadata: The metadata of this RunSerializer.  # noqa: E501
        :type metadata: WorkspaceMetadataSerializer
        :param spec: The spec of this RunSerializer.  # noqa: E501
        :type spec: RunSpecSerializer
        :param id: The id of this RunSerializer.  # noqa: E501
        :type id: str
        :param state: The state of this RunSerializer.  # noqa: E501
        :type state: str
        :param uptime: The uptime of this RunSerializer.  # noqa: E501
        :type uptime: int
        :param create_at: The create_at of this RunSerializer.  # noqa: E501
        :type create_at: str
        :param last_update: The last_update of this RunSerializer.  # noqa: E501
        :type last_update: str
        """
        self.openapi_types = {
            'metadata': WorkspaceMetadataSerializer,
            'spec': RunSpecSerializer,
            'id': str,
            'state': str,
            'uptime': int,
            'create_at': str,
            'last_update': str
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'spec': 'spec',
            'id': 'id',
            'state': 'state',
            'uptime': 'uptime',
            'create_at': 'create_at',
            'last_update': 'last_update'
        }

        self._metadata = metadata
        self._spec = spec
        self._id = id
        self._state = state
        self._uptime = uptime
        self._create_at = create_at
        self._last_update = last_update

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Run of this RunSerializer.  # noqa: E501
        :rtype: RunSerializer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self):
        """Gets the metadata of this RunSerializer.


        :return: The metadata of this RunSerializer.
        :rtype: WorkspaceMetadataSerializer
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this RunSerializer.


        :param metadata: The metadata of this RunSerializer.
        :type metadata: WorkspaceMetadataSerializer
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata

    @property
    def spec(self):
        """Gets the spec of this RunSerializer.


        :return: The spec of this RunSerializer.
        :rtype: RunSpecSerializer
        """
        return self._spec

    @spec.setter
    def spec(self, spec):
        """Sets the spec of this RunSerializer.


        :param spec: The spec of this RunSerializer.
        :type spec: RunSpecSerializer
        """
        if spec is None:
            raise ValueError("Invalid value for `spec`, must not be `None`")  # noqa: E501

        self._spec = spec

    @property
    def id(self):
        """Gets the id of this RunSerializer.


        :return: The id of this RunSerializer.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RunSerializer.


        :param id: The id of this RunSerializer.
        :type id: str
        """

        self._id = id

    @property
    def state(self):
        """Gets the state of this RunSerializer.


        :return: The state of this RunSerializer.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this RunSerializer.


        :param state: The state of this RunSerializer.
        :type state: str
        """
        allowed_values = ["CREATED", "STARTING", "RUNNING", "ABORTED", "SUCCEEDED", "FAILED"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def uptime(self):
        """Gets the uptime of this RunSerializer.


        :return: The uptime of this RunSerializer.
        :rtype: int
        """
        return self._uptime

    @uptime.setter
    def uptime(self, uptime):
        """Sets the uptime of this RunSerializer.


        :param uptime: The uptime of this RunSerializer.
        :type uptime: int
        """

        self._uptime = uptime

    @property
    def create_at(self):
        """Gets the create_at of this RunSerializer.


        :return: The create_at of this RunSerializer.
        :rtype: str
        """
        return self._create_at

    @create_at.setter
    def create_at(self, create_at):
        """Sets the create_at of this RunSerializer.


        :param create_at: The create_at of this RunSerializer.
        :type create_at: str
        """

        self._create_at = create_at

    @property
    def last_update(self):
        """Gets the last_update of this RunSerializer.


        :return: The last_update of this RunSerializer.
        :rtype: str
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update):
        """Sets the last_update of this RunSerializer.


        :param last_update: The last_update of this RunSerializer.
        :type last_update: str
        """

        self._last_update = last_update
